### ISSUE TITLE
Issue from last update 11.0.7

### ISSUE THREAD

**Issue by iamlucas13** [RotherOSS/MailAccount-OAuth2#7]
![image](https://github.com/user-attachments/assets/180ce0a6-1ded-4b93-893e-45770ab53ed4)

Hello I have this issue from last update.

Do you have any idea? I tried to reinstall mailaccount Oauth2 package. It's working great without but not with... 

Lucas

**Comment by svenoe** [comment]
Hi Lucas,

just from having the package installed, we cannot confirm this. Please when submitting an issue, provide some instructions on how to reproduce the behavior on a new and clean test system. (And some log messages wouldn't hurt, either, but mainly we have to be able to reproduce the problem.)

I'll close the issue for now, if you update the info you can write a short message here, and I can reopen it.

Best regards, Sven
